workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.myapp" # Ersetze mit deinem Paketnamen
      groups:
        - google_credentials # Stelle sicher, dass diese Env-Var existiert

    working_directory: app  # <<< Wichtig: Damit Codemagic im richtigen Ordner arbeitet!

    scripts:
      - echo "📂 Aktuelles Verzeichnis anzeigen"
      - pwd  # Zeigt das aktuelle Verzeichnis an
      - echo "📄 Vorhandene Dateien anzeigen"
      - ls -la  # Zeigt, ob pubspec.yaml existiert
      - echo "📦 Prüfen, ob pubspec.yaml existiert"
      - if [ ! -f "pubspec.yaml" ]; then echo "❌ ERROR: pubspec.yaml nicht gefunden!"; exit 1; fi
      - echo "📦 Running Flutter Clean"
      - flutter clean
      - echo "📦 Running Flutter Pub Get"
      - flutter pub get
      - echo "🔧 Building APK"
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk  # Exakter Pfad zur APK-Datei

    publishing:
      android:
        artifacts:
          - app-release.apk
        signing:
          credentials: $CM_KEYSTORE_PATH
          keystore_password: $CM_KEYSTORE_PASSWORD
          key_alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD
