workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.myapp"
      groups:
        - google_credentials

    scripts:
      - echo "📦 Installing http Package"
      - flutter pub add http:^1.1.0  # NEU: Fügt die richtige Version von http hinzu
      - echo "📦 Running Flutter Clean"
      - flutter clean
      - echo "📦 Running Flutter Pub Get"
      - flutter pub get
      - echo "🔧 Building APK"
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      android:
        artifacts:
          - app-release.apk
        signing:
          credentials: $CM_KEYSTORE_PATH
          keystore_password: $CM_KEYSTORE_PASSWORD
          key_alias: $CM_KEY_ALIAS
          key_password: $CM_KEY_PASSWORD
